---
- name: "CV | Promote all Composite content-views through lifecycle environment path"
  command: >
    hammer content-view version promote --organization {{ org }}
    --to-lifecycle-environment-id {{ item.1.ID }}
    --content-view-id {{ item[0]["Content View ID"] }}
    --version {{ item.2.Version }}
    --description "promoted on {{ ansible_date_time.date }} {{ ansible_date_time.time }}"
  with_nested:
    - "{{ JSON_ccv_list }}"
    - "{{ JSON_lifecycle_env }}"
    - "{{ JSON_oldest_ccv_version }}"
  when: item.1.Name != 'Library' and item.2.Name.find("item.0.Name") != -1
  tags:
    - ccv
    - promote
