---
- name: "CV | Publish all composite content-views"
  command: >
    hammer content-view publish --id {{ item.ID }}
    --organization {{ org }}
    --description "published on {{ vansible_date_time.date }} {{ ansible_date_time.time }}"
  with_items: "{{ JSON_ccv_list }}"
  tags:
    - cv
    - publish
