---
- name: "CV | Get composite content-view ID list"
  command: >
    hammer --output json content-view list --organization {{ org }}
    --composite no --composite yes
  register: ccv_list
  tags:
    - cv
    - facts

- name: "CV | Set composite fact for content-view list"
  set_fact:
    JSON_ccv_list="{{ ccv_list.stdout | from_json }}"

- debug:
    var: JSON_ccv_list
