---
- name: "CV | Get content-view ID list"
  command: >
     hammer --output json content-view list
     --organization {{ org }} --composite no
  register: cv_list
  tags:
    - cv
    - facts

- name: "CV | Set fact for content-view list"
  set_fact:
    JSON_cv_list="{{ cv_list.stdout | from_json }}"

- debug:
  var: JSON_cv_list
