---
- name: "Create composite content-view purge facts"
  set_fact:
     JSON_ccv_purge_list = "{{ item }}"
  with_items: "{{ JSON_ccv_list }}"
  when: item.Version|int < "{{ item.Version|int - purge|int }}"
  tags:
    - purge
    - facts
