---
- name: "CV | Get lifecycle environment list"
  command: >
    hammer --output json lifecycle-environment list --organization {{ org }}
    --order "ID ASC"
  register: lifecycle_env_list
  tags:
    - cv
    - facts

- name: "CV | Set fact for lifecycle environment list"
  set_fact:
      JSON_lifecycle_env="{{ item }}"
  with_items: "{{ lifecycle_env_list.stdout | from_json }}"

- debug:
    var: JSON_lifecycle_env
